[package]
name = "enum_expand"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = {version = "2.0.90", features = ["full"]}

[dev-dependencies]
snafu = { version = "0.8.5", features = ["backtrace"] }